package ru.serverastus.monitor.данные.локаль

// Сгенерировано: 200 строк словаря (фрагмент 4).
internal val ЧастьАнглийский4: Map<String, String> = mapOf(
    "Проверяются код ответа и срок действия сертификата. Ожидаются коды 200, 301 и 302." to "The response code and the certificate expiry are checked. Codes 200, 301 and 302 are expected.",
    "Проверяю…" to "Checking…",
    "Программа" to "Program",
    "Продолжить" to "Resume",
    "Пропустить" to "Skip",
    "Пропустить шаг" to "Skip step",
    "Протоколы TCP и UDP" to "TCP and UDP protocols",
    "Профиль «{1}» будет удалён." to "Profile «{1}» will be deleted.",
    "Процессов" to "Processes",
    "Процессы (топ по ЦП и памяти)" to "Processes (top by CPU and memory)",
    "Прочих обновлений: {1}" to "Other updates: {1}",
    "Работа восстановлена" to "Back online",
    "Работает ядро {1}, а установлено {2}." to "Kernel {1} is running, while {2} is installed.",
    "Работающие службы не найдены: проверьте, что на сервере есть systemd" to "No running services found: check whether systemd exists on the server",
    "Разблокировать" to "Unban",
    "Разблокировать адрес {1} на сервере?" to "Unban the address {1} on the server?",
    "Размер" to "Size",
    "Размер истории" to "History size",
    "Размер уже заметный. Предел в 300 МБ хранит историю за пару недель и держит диск свободным." to "The size is already noticeable. A 300 MB limit keeps a couple of weeks of history and keeps the disk free.",
    "Разработчик" to "Developer",
    "Рекомендации ({1})" to "Recommendations ({1})",
    "Рекомендации (по важности)" to "Recommendations (by importance)",
    "Рекомендации по оптимизации" to "Optimisation recommendations",
    "Рекомендаций нет — параметры сети в порядке." to "No recommendations — network parameters are in order.",
    "Ротация журналов" to "Log rotation",
    "Ротация журналов выключена" to "Log rotation is disabled",
    "С ним клиенты отдают первый запрос сразу вместе с SYN — сайт отвечает на один обмен пакетами быстрее. Включайте, если сайт доступен по HTTPS." to "With it, clients send the first request together with the SYN — the site responds one round trip sooner. Enable it if the site is available over HTTPS.",
    "Сайт" to "Site",
    "Сайтов" to "Sites",
    "Сайты" to "Sites",
    "Сайты для проверки" to "Sites to check",
    "Сайты и порты не настроены" to "Sites and ports are not configured",
    "Сайты и порты: {1} из {2}" to "Sites and ports: {1} of {2}",
    "Сайты не найдены: на сервере нет конфигурации nginx/Apache с доменами" to "No sites found: the server has no nginx/Apache configuration with domains",
    "Сайты, порты и службы" to "Sites, ports and services",
    "Сайты: {1}" to "Sites: {1}",
    "Сбои" to "Failures",
    "Сбой" to "Failure",
    "Сбой в опросе: {1}" to "Polling failure: {1}",
    "Сбой в цикле опроса: {1}" to "Failure in the polling loop: {1}",
    "Сбойные юниты" to "Failed units",
    "Сбойный юнит" to "Failed unit",
    "Сбойных служб" to "Failed services",
    "Сбойных служб: {1}" to "Failed services: {1}",
    "Сбросить" to "Reset",
    "Сбросить настройки" to "Reset settings",
    "Сбросить настройки?" to "Reset the settings?",
    "Сбросов в минуту" to "Resets per minute",
    "Сбросов соединений" to "Connection resets",
    "Сведения" to "Info",
    "Свернуть" to "Collapse",
    "Свободно" to "Free",
    "Свободно {1} из {2}. При заполнении выше 90 % часть служб перестаёт писать данные и падает." to "Free {1} of {2}. Above 90 % full some services stop writing data and fail.",
    "Свободно {1}. Пора почистить старые журналы, резервные копии и кэш пакетов." to "Free {1}. It is time to clean up old journals, backups and the package cache.",
    "Свободных локальных портов {1}, половина занята соединениями в состоянии TIME_WAIT — новые исходящие подключения могут не открываться." to "Free local ports {1}, half of them taken by connections in TIME_WAIT — new outgoing connections may fail to open.",
    "Связь есть. {1}" to "Connected. {1}",
    "Связь есть: хост «{1}», пользователь «{2}»" to "Connected: host «{1}», user «{2}»",
    "Связь с сервером" to "Server connectivity",
    "Связь с сервером есть" to "The server is reachable",
    "Связь с сервером потеряна" to "Connection to the server lost",
    "Связь с сервером потеряна — {1}" to "Connection to the server lost — {1}",
    "Сегментов отправлено" to "Segments sent",
    "Сегментов принято" to "Segments received",
    "Сегменты так и не дошли до получателя после всех попыток — соединения рвутся. Вместе с высокой долей повторных передач это указывает на перегруженный канал." to "Segments never reached the receiver after all attempts — connections are breaking. Together with a high retransmission share this points to an overloaded link.",
    "Сейчас нет активных ручных блокировок." to "There are no active manual bans right now.",
    "Сервер" to "Server",
    "Сервер без имени" to "Unnamed server",
    "Сервер в порядке, но есть что подтянуть — смотрите советы ниже." to "The server is in order, but there is room for improvement — see the advice below.",
    "Сервер вернул неполный ответ на запрос данных безопасности" to "The server returned an incomplete response to the security data request",
    "Сервер вернул неполный ответ на запрос диагностики сети" to "The server returned an incomplete response to the network diagnostics request",
    "Сервер вернул неполный ответ на запрос обслуживания" to "The server returned an incomplete response to the maintenance request",
    "Сервер вернул неполный ответ на запрос подробностей" to "The server returned an incomplete response to the details request",
    "Сервер вернул неполный ответ — возможно, команды ограничены оболочкой" to "The server returned an incomplete response — the commands may be restricted by the shell",
    "Сервер вернул неполный ответ — повторяю запрос (попытка {1} из {2})" to "The server returned an incomplete response — retrying the request (attempt {1} of {2})",
    "Сервер ждёт перезагрузки" to "The server is waiting for a reboot",
    "Сервер не вернул параметры сети" to "The server did not return the network parameters",
    "Сервер не настроен" to "The server is not configured",
    "Сервер не настроен — откройте мастер настройки" to "The server is not configured — open the setup wizard",
    "Сервер не ответил" to "The server did not respond",
    "Сервер ответил ошибкой {1}{2}{3}" to "The server responded with error {1}{2}{3}",
    "Сервер отклонил логин или пароль — проверьте настройки подключения" to "The server rejected the login or password — check the connection settings",
    "Сервер требует внимания: оценка обслуживания {1} из 100 ({2})" to "The server needs attention: maintenance score {1} of 100 ({2})",
    "Сервер удалён: {1}" to "Server deleted: {1}",
    "Серверов пока нет" to "No servers yet",
    "Серверы" to "Servers",
    "Сетевые интерфейсы" to "Network interfaces",
    "Сеть" to "Network",
    "Сеть недоступна" to "Network unavailable",
    "Сеть работает ровно, но есть что подтянуть в настройках." to "The network runs smoothly, but the settings could use some tuning.",
    "Синхронизация времени" to "Time synchronisation",
    "Система" to "System",
    "Система оставила флаг /var/run/reboot-required." to "The system left the /var/run/reboot-required flag.",
    "Скопировать отчёт" to "Copy report",
    "Скопируйте config.json из настольной версии в каталог приложения (по USB) и нажмите «Загрузить из файла» — подтянутся адрес, пароль, сайты, порты и службы." to "Copy config.json from the desktop version into the application directory (over USB) and press «Load from file» — the address, password, sites, ports and services will be imported.",
    "Скорее всего один из сервисов пишет слишком подробно." to "Most likely one of the services logs too verbosely.",
    "Скорости (в секунду и в минуту) появятся после второго опроса сети — сейчас показаны только накопительные счётчики." to "Rates (per second and per minute) appear after the second network poll — only cumulative counters are shown for now.",
    "Скорость отправки" to "Send rate",
    "Скорость получения" to "Receive rate",
    "Служб" to "Services",
    "Служба «{1}» {2}" to "Service «{1}» {2}",
    "Служба времени" to "Time service",
    "Служба запущена ({1})" to "Service started ({1})",
    "Служба запущена вручную." to "Service started manually.",
    "Служба не работает: {1} ({2})" to "Service is down: {1} ({2})",
    "Служба остановлена вручную." to "Service stopped manually.",
    "Служба перезапущена вручную." to "Service restarted manually.",
    "Служба, связанная с сайтом" to "Service related to the site",
    "Службы" to "Services",
    "Службы systemd" to "systemd services",
    "Службы systemd: {1}" to "systemd services: {1}",
    "Службы и время" to "Services and time",
    "Службы сервера" to "Server services",
    "Слушающих портов" to "Listening ports",
    "Сначала заполните адрес и пользователя на шаге «Сервер»" to "First fill in the address and user on the «Server» step",
    "Сначала настройте сервер в мастере настройки" to "Configure the server in the setup wizard first",
    "Снять блокировку" to "Lift the ban",
    "Событий ещё нет" to "No events yet",
    "Событий пока нет" to "No events yet",
    "Соединение отклонено (порт закрыт)" to "Connection refused (port closed)",
    "Соединение отклонено (сервер не слушает порт)" to "Connection refused (the server is not listening on the port)",
    "Соединение разорвано удалённой стороной" to "Connection closed by the remote side",
    "Соединений сейчас" to "Connections now",
    "Соединения TIME_WAIT" to "TIME_WAIT connections",
    "Соединения висят в TIME_WAIT, а net.ipv4.tcp_tw_reuse=0 — порты не переиспользуются. Для сервера с большим числом коротких подключений переиспользование безопасно и полезно." to "Connections linger in TIME_WAIT while net.ipv4.tcp_tw_reuse=0 — ports are not reused. For a server with many short connections reuse is both safe and useful.",
    "Соединения по данным ss" to "Connections according to ss",
    "Соединения с большой задержкой (мобильные клиенты, другие города) не смогут разогнаться — буфера не хватает. Для сервера с сайтами хватает 16 МиБ." to "Connections with high latency (mobile clients, other cities) will not be able to ramp up — the buffer is too small. For a site server 16 MiB is enough.",
    "Сокетов всего" to "Sockets total",
    "Состояние" to "State",
    "Состояние сети" to "Network state",
    "Состояние сети восстановилось: оценка {1} из 100 ({2})" to "Network state recovered: score {1} of 100 ({2})",
    "Состояние сети ухудшилось: оценка {1} из 100 ({2})" to "Network state degraded: score {1} of 100 ({2})",
    "Сохранено серверов: {1}" to "Servers saved: {1}",
    "Сохранить в файл" to "Save to file",
    "Сохранить всё равно" to "Save anyway",
    "Сохранить настройки" to "Save settings",
    "Список накопителей сервер не вернул" to "The server did not return the list of drives",
    "Список процессов появится после подробного опроса" to "The process list appears after a detailed poll",
    "Список пуст" to "The list is empty",
    "Список сайтов и портов пуст — заполните его в настройках" to "The list of sites and ports is empty — fill it in the settings",
    "Список сайтов, портов и служб можно не вводить руками: на шаге каждого списка есть кнопка поиска — приложение прочитает конфигурацию nginx/Apache, слушающие порты и работающие службы прямо на сервере." to "You do not have to type the list of sites, ports and services manually: each list step has a search button — the app reads the nginx/Apache configuration, listening ports and running services directly on the server.",
    "Список служб пуст или ещё не получен" to "The service list is empty or has not been received yet",
    "Срабатываний ограничителя памяти" to "Memory limiter hits",
    "Средняя нагрузка" to "Average load",
    "Столько ждёт последний FIN. 30 секунд уменьшает число «зависших» сокетов без риска потерять данные." to "The last FIN waits this long. 30 seconds reduces the number of «stuck» sockets without risking data loss.",
    "Столько пакетов больше никому не нужны (устаревшие зависимости). Перед удалением посмотрите список — иногда там ядро, к которому хочется откатиться." to "This many packages are unwanted by anyone (obsolete dependencies). Check the list before removing — sometimes the previous kernel you may want to roll back to is there.",
    "Счётчики в норме: потерь и переполнений нет." to "Counters are normal: no losses or overflows.",
    "Таблица соединений (conntrack)" to "Connection table (conntrack)",
    "Таблица соединений заполнена на {1}" to "Connection table is {1} full",
    "Таймаут подключения, секунд" to "Connection timeout, seconds",
    "Таймаутов TCP" to "TCP timeouts",
    "Телефон перезагружен — запускаю мониторинг" to "Phone rebooted — starting monitoring",
    "Температура" to "Temperature",
    "Тестовое оповещение" to "Test alert",
    "Тестовое событие отправлено" to "Test event sent",
    "Тестовое сообщение отправлено" to "Test message sent",
    "Техжурнал приложения" to "Application tech log",
    "Техжурнал сервера" to "Server technical log",
    "ТиБ" to "TiB",
    "Токен бота" to "Bot token",
    "Точка монтирования диска" to "Disk mount point",
    "Тревоги" to "Alerts",
    "У порта №{1} не указан хост" to "Port #{1} has no host",
    "У сайта №{1} не указан адрес" to "Site #{1} has no address",
    "Убрать" to "Remove",
    "Уведомления" to "Notifications",
    "Удалить" to "Delete",
    "Удалить порт" to "Delete port",
    "Удалить сайт" to "Delete site",
    "Удалить сервер?" to "Delete server?",
    "Узел недоступен (нет маршрута)" to "Host unreachable (no route)",
    "Управление перегрузкой TCP" to "TCP congestion control",
    "Управление перегрузкой TCP: {1}" to "TCP congestion control: {1}",
    "Успех" to "Success",
    "Успехи" to "Successes",
    "Установлено пакетов" to "Packages installed",
    "Установлено ядро новее работающего ({1})." to "A newer kernel than the running one is installed ({1}).",
    "Файл" to "File",
    "Файл ещё не создан: {1}" to "The file has not been created yet: {1}",
    "Файл ключа (необязательно)" to "Key file (optional)",
    "Файл ключа (путь на телефоне)" to "Key file (path on the phone)",
    "Файл настроек" to "Settings file",
    "Файлы и действия" to "Files and actions",
    "Хост" to "Host",
    "Хранить дней" to "Keep for days",
    "Хранить историю, дней" to "Keep history, days",
    "ЦП" to "CPU",
    "ЦП {1}" to "CPU {1}",
    "ЦП {1} · ОЗУ {2}" to "CPU {1} · RAM {2}",
    "ЦП, %" to "CPU, %",
    "Целей проверено" to "Targets checked",
    "Цели" to "Targets",
    "Цель недоступна — {1}" to "Target unavailable — {1}",
    "Часовой пояс" to "Time zone",
    "Часть данных вытеснена на диск. Не критично, но стоит присмотреться к потреблению памяти." to "Part of the data was pushed out to disk. Not critical, but memory consumption is worth a closer look.",
    "Часть показателей вышла за норму — посмотрите рекомендации ниже." to "Some metrics are out of range — see the recommendations below.",
    "Часы сервера расходятся с точным временем: поедут метки в журналах, а проверка сертификатов и блокировки fail2ban начнут ошибаться." to "The server clock drifts from exact time: log timestamps will be off, and certificate checks and fail2ban bans will start misbehaving.",
    "Чат (chat_id)" to "Chat (chat_id)",
    "Что дальше" to "What next",
    "Что понадобится" to "What you will need",
    "Что сделать" to "What to do",
)
