package ru.serverastus.monitor.данные.локаль

// Сгенерировано: 200 строк словаря (фрагмент 2).
internal val ЧастьАнглийский2: Map<String, String> = mapOf(
    "Внутренняя ошибка проверки: {1}" to "Internal check error: {1}",
    "Восстановление" to "Recovery",
    "Время" to "Time",
    "Время не синхронизировано" to "Time is not synchronised",
    "Время опроса" to "Poll time",
    "Время ответа" to "Response time",
    "Время ответа, последние {1} проверок" to "Response time, last {1} checks",
    "Время, мс" to "Time, ms",
    "Все" to "All",
    "Все записи журнала ({1} шт.) будут удалены из базы без возможности восстановления. Настройки и история метрик не затрагиваются." to "All journal entries ({1}) will be deleted from the database and cannot be restored. Settings and metric history are not affected.",
    "Всего" to "Total",
    "Всего блокировок" to "Total bans",
    "Всего попыток входа" to "Total login attempts",
    "Выгружаю…" to "Exporting…",
    "Выйти" to "Exit",
    "Выполняется" to "In progress",
    "Выше 60 °C накопитель живёт заметно меньше. Проверьте продув корпуса и температуру в помещении." to "Above 60 °C a drive lives noticeably shorter. Check the case airflow and the room temperature.",
    "ГиБ" to "GiB",
    "Готово" to "Done",
    "Готово: файлов {1} в папке «экспорт»" to "Done: {1} files in the «экспорт» folder",
    "Да, {1}" to "Yes, {1}",
    "Да, обнулить" to "Yes, clear it",
    "Далее" to "Next",
    "Данные интерфейсов не получены" to "Interface data was not received",
    "Данные появятся после первого аудита (по умолчанию раз в 10 минут)" to "Data appears after the first audit (once every 10 minutes by default)",
    "Данные появятся после первого опроса безопасности" to "Data appears after the first security poll",
    "Данные появятся после первого опроса сети (по умолчанию раз в 30 секунд)" to "Data appears after the first network poll (once every 30 seconds by default)",
    "Датаграмм отправлено" to "Datagrams sent",
    "Датаграмм принято" to "Datagrams received",
    "Датаграммы пришли на порт, который никто не слушает — обычно так выглядят сканирования. Если это должен быть рабочий сервис, проверьте, запущен ли он." to "Datagrams arrived at a port nobody listens on — this usually looks like scanning. If a real service should be there, check whether it is running.",
    "Датаграммы теряются или не помещаются в буфер: ошибок {1}, переполнений буфера приёма {2}, буфера отправки {3}. Для DNS, WireGuard и игровых сервисов это прямые потери запросов." to "Datagrams are lost or do not fit the buffer: {1} errors, {2} receive buffer overflows, {3} send buffer overflows. For DNS, WireGuard and game services these are direct request losses.",
    "Два часа сервер считает оборванное соединение живым. Для веб-сервера разумно 300 секунд — быстрее освобождаются сокеты и память." to "For two hours the server treats a dropped connection as alive. For a web server 300 seconds is reasonable — sockets and memory are freed sooner.",
    "Действие выполнено." to "Action completed.",
    "Диагностика сети (TCP и UDP)" to "Network diagnostics (TCP and UDP)",
    "Диагностика сети сервера · {1}" to "Server network diagnostics · {1}",
    "Диапазон локальных портов" to "Local port range",
    "Диск" to "Disk",
    "Диск {1}" to "Disk {1}",
    "Диск всего, байт" to "Disk total, bytes",
    "Диск занят" to "Disk usage",
    "Диск занято, байт" to "Disk used, bytes",
    "Диск заполнен на {1} %" to "Disk is {1} % full",
    "Диск нагрет до {1} °C" to "Disk heated up to {1} °C",
    "До {1} % считается нормой. Значение выше говорит о начинающихся потерях в канале или о перегрузке сетевой карты." to "Up to {1} % is considered normal. A higher value points to emerging channel loss or to NIC overload.",
    "Добавить" to "Add",
    "Добавить порт" to "Add port",
    "Добавить сайт" to "Add site",
    "Добавить службу" to "Add service",
    "Добавлено: {1}" to "Added: {1}",
    "Добавьте сервер мастером настройки: приложение проверит подключение и найдёт на нём сайты, порты и службы." to "Add a server with the setup wizard: the app tests the connection and discovers its sites, ports and services.",
    "Добро пожаловать" to "Welcome",
    "Долгий старт обычно означает службы, которые ждут недоступную сеть или диск. Долгую загрузку видно в детальном отчёте systemd." to "A slow boot usually means services waiting for an unreachable network or disk. A long boot is visible in the detailed systemd report.",
    "Доступно" to "Available",
    "Доступно обновлений" to "Updates available",
    "Доступно сейчас" to "Currently available",
    "Доступность за сутки" to "Availability over 24 hours",
    "Единичные отбросы из очереди прослушивания — обычно всплеск подключений от сканеров. Если счётчик быстро растёт, увеличьте очередь." to "Isolated listen-queue drops are usually a burst of scanner connections. If the counter grows quickly, increase the queue.",
    "Есть серьёзные сбои: примените важные рекомендации ниже." to "There are serious failures: apply the important recommendations below.",
    "Ждём первый ответ сервера…" to "Waiting for the server's first response…",
    "Журнал" to "Journal",
    "Журнал systemd" to "systemd journal",
    "Журнал systemd занимает {1}" to "systemd journal occupies {1}",
    "Журнал событий" to "Event journal",
    "Журнал событий обнулён: удалено записей — {1}" to "Event log cleared: records deleted — {1}",
    "Журналы и место" to "Journals and disk space",
    "За последний час" to "Over the last hour",
    "Заблокировано сейчас" to "Banned now",
    "Заблокировать" to "Ban",
    "Заблокировать IP" to "Ban IP",
    "Загрузить из файла" to "Load from file",
    "Загрузка занимает {1} с" to "Boot takes {1} s",
    "Загрузка процессора" to "CPU load",
    "Загрузка процессора, %" to "CPU load, %",
    "Загрузка сервера" to "Server load",
    "Задержка SSH" to "SSH latency",
    "Задержка отклика" to "Response latency",
    "Закрытие соединения — {1} с" to "Connection close — {1} s",
    "Закрытий из-за памяти" to "Closes due to memory",
    "Закрытий по нехватке памяти: {1}, срабатываний ограничителя: {2}. Соединения обрываются досрочно." to "Closes due to memory shortage: {1}, limit hits: {2}. Connections are dropped early.",
    "Замер за" to "Measured over",
    "Замечаний нет: обновления установлены, службы здоровы, журналы под контролем." to "No findings: updates are installed, services are healthy, journals are under control.",
    "Занятая память" to "Used memory",
    "Занятая память, %" to "Used memory, %",
    "Занято" to "Used",
    "Занято на разделе" to "Used on partition",
    "Занятое место на диске" to "Disk usage",
    "Занятое место на диске, %" to "Disk space used, %",
    "Запас ещё есть, но растёт он обычно незаметно. Полезно посмотреть, что занимает место." to "There is still headroom, but it usually grows unnoticed. It is worth checking what takes up the space.",
    "Записей {1} из {2}. Запас есть, но при всплеске посетителей он закончится — стоит поднять предел заранее." to "Entries {1} of {2}. There is headroom, but a traffic spike will exhaust it — raise the limit in advance.",
    "Записей {1} из {2}. При заполнении ядро перестанет принимать новые соединения — сайт будет недоступен." to "Entries {1} of {2}. Once it fills up the kernel stops accepting new connections — the site will be unavailable.",
    "Записей в таблице соединений" to "Entries in the connection table",
    "Записей нет" to "No entries",
    "Запускать мониторинг при загрузке телефона" to "Start monitoring when the phone boots",
    "Запустить" to "Start",
    "Защита от переполнения очереди SYN" to "SYN queue overflow protection",
    "Защита от подбора паролей" to "Password brute-force protection",
    "Здоровье дисков" to "Drive health",
    "Здоровье дисков не прочитано: {1}" to "Drive health could not be read: {1}",
    "Из них безопасности" to "Security updates among them",
    "Изменить" to "Edit",
    "Имена как в systemctl, например: nginx, mysql, ssh, fail2ban." to "Names as in systemctl, for example: nginx, mysql, ssh, fail2ban.",
    "Имя" to "Name",
    "Имя сервера" to "Server name",
    "Имя сервера нужно, когда их несколько: так проще выбрать нужный в списке. Если оставить пустым, будет показан адрес сервера." to "A server name matters when there are several: it makes picking the right one from the list easier. If left empty, the server address is shown instead.",
    "Имя службы" to "Service name",
    "Имя службы, например nginx.service" to "Service name, for example nginx.service",
    "Интервалы опроса, секунд" to "Poll intervals, seconds",
    "Интерфейс уже передавал данные, а сейчас носителя нет: оборван кабель, выключен порт коммутатора или сработала защита сервиса восстановления линка. Проверьте кабель и порт." to "The interface was already passing traffic but has no carrier now: the cable is broken, the switch port is off, or the link-recovery service tripped. Check the cable and the port.",
    "Интерфейсы" to "Interfaces",
    "Исправить" to "Fix",
    "Исправлений уязвимостей среди них нет — это плановое обслуживание. Поставьте их при удобном случае, отдельного срочного окна не требуется." to "None of them fix a vulnerability — this is routine maintenance. Install them when convenient; no urgent window is needed.",
    "История и журнал этого сервера останутся на диске: если добавить его снова, данные вернутся." to "The history and log of this server stay on disk: add it again and the data comes back.",
    "История мониторинга" to "Monitoring history",
    "История сервера" to "Server history",
    "Итоги" to "Summary",
    "Ищу…" to "Searching…",
    "Кандидаты на авт. удаление" to "Auto-removal candidates",
    "Каталог /var/log" to "/var/log directory",
    "Каталог /var/log без журнала" to "/var/log directory without the systemd journal",
    "Каталог журналов вырос. Проверьте ротацию и подробность логирования у отдельных служб." to "The journal directory grew. Check rotation and the logging verbosity of individual services.",
    "Каталог приложения" to "Application directory",
    "КиБ" to "KiB",
    "Кнопка сначала сохраняет настройки, а затем проверяет подключение по SSH." to "The button first saves the settings and then tests the SSH connection.",
    "Когда значение превысит порог, в журнал попадёт предупреждение, а если включены уведомления — придёт сообщение на телефон." to "When the value exceeds the threshold, a warning is written to the journal and, if notifications are enabled, a message arrives on the phone.",
    "Код" to "Code",
    "Код ответа {1}, ожидался {2}{3}" to "Response code {1}, expected {2}{3}",
    "Команда для «{1}» отправлена на сервер…" to "The command for «{1}» was sent to the server…",
    "Команда скопирована" to "Command copied",
    "Команды выполняются на сервере по SSH от имени sudo и действуют до перезагрузки. Чтобы сохранить их навсегда, запишите строки в /etc/sysctl.d/99-сеть.conf и выполните sysctl --system (или перезагрузите сервер)." to "The commands run on the server over SSH as sudo and last until reboot. To keep them permanently, write the lines into /etc/sysctl.d/99-сеть.conf and run sysctl --system (or reboot the server).",
    "Команды выполняются на сервере по SSH. Обновления и перезагрузка — ваше решение: приложение только показывает, что накопилось." to "The commands run on the server over SSH. Updates and reboots are your decision: the app only shows what has accumulated.",
    "Копировать" to "Copy",
    "Крупнее всего: {1}. " to "Largest: {1}. ",
    "Крупнейшие файлы журналов" to "Largest journal files",
    "Линк на «{1}» опущен" to "Link on «{1}» is down",
    "Линк опущен на «{1}» — проверьте кабель, порт коммутатора и службу восстановления линка." to "Link is down on «{1}» — check the cable, the switch port and the link-recovery service.",
    "Логин и пароль (или файл ключа)" to "Login and password (or key file)",
    "Максимальный буфер отправки" to "Maximum send buffer",
    "Максимальный буфер отправки всего {1}" to "Maximum send buffer is only {1}",
    "Максимальный буфер приёма" to "Maximum receive buffer",
    "Максимальный буфер приёма всего {1}" to "Maximum receive buffer is only {1}",
    "Малая очередь приёма сетевой карты: {1}" to "NIC receive queue is small: {1}",
    "Мастер можно открыть снова: вкладка «Настройки» → «Мастер настройки»." to "The wizard can be opened again: the «Settings» tab → «Setup wizard».",
    "Мастер настройки" to "Setup wizard",
    "Мастер настройки закрыт без изменений" to "Setup wizard closed without changes",
    "Мастер настройки пропущен — настройка отложена" to "Setup wizard skipped — setup postponed",
    "Мастер настройки: сервер «{1}», сайтов {2}, портов {3}, служб {4}" to "Setup wizard: server «{1}», {2} sites, {3} ports, {4} services",
    "Медленный старт после простоя" to "Slow start after idle",
    "Метрики сервера" to "Server metrics",
    "МиБ" to "MiB",
    "Мобильная версия повторяет настольную: те же интервалы, пороги, тексты событий и формат истории." to "The mobile version mirrors the desktop one: the same intervals, thresholds, event texts and history format.",
    "Модуль BBR уже доступен. BBR держит скорость на каналах с потерями, тогда как {1} резко снижает её при любой потере пакета." to "The BBR module is already available. BBR keeps throughput on lossy links, whereas {1} drops it sharply on any packet loss.",
    "Мониторить сервер" to "Monitor server",
    "На закрытые порты" to "To closed ports",
    "На паузе" to "Paused",
    "На странице нет текста «{1}»" to "The page does not contain the text «{1}»",
    "На что обратить внимание" to "What to look at",
    "Нагрузка 1 мин" to "Load average 1 min",
    "Назад" to "Back",
    "Найти порты на сервере" to "Find ports on the server",
    "Найти сайты на сервере" to "Find sites on the server",
    "Накопились важные дела: обновления, сбои или место на диске." to "Important matters have piled up: updates, failures or disk space.",
    "Накопились обновления пакетов. Чем дольше тянуть, тем больше шансов на конфликт версий." to "Package updates have accumulated. The longer you wait, the higher the chance of a version conflict.",
    "Накопители" to "Drives",
    "Накопители {1} в системе есть, но ни один раздел на них не смонтирован. На свободном диске удобно держать резервные копии." to "The drive {1} exists in the system, but none of its partitions is mounted. A spare disk is a convenient place for backups.",
    "Накопители и SMART" to "Drives and SMART",
    "Накопительно это {1} принятых пакетов. {2}" to "Cumulatively this is {1} received packets. {2}",
    "Настроить позже" to "Set up later",
    "Настройка сервера" to "Server setup",
    "Настройки" to "Settings",
    "Настройки ServerMonitor" to "ServerMonitor settings",
    "Настройки загружены" to "Settings loaded",
    "Настройки загружены из файла" to "Settings loaded from file",
    "Настройки можно сохранить и так — их всегда можно поправить на вкладке «Настройки»." to "You can save the settings like this too — they can always be corrected on the «Settings» tab.",
    "Настройки сброшены к значениям по умолчанию" to "Settings reset to defaults",
    "Настройки сохранены" to "Settings saved",
    "Начать" to "Start",
    "Начать мониторинг" to "Start monitoring",
    "Не используется накопитель: {1}" to "Unused drive: {1}",
    "Не повторять одно событие, минут" to "Do not repeat the same event, minutes",
    "Не принято соединений: {1}, отброшено SYN: {2}. Клиенты видят таймаут при подключении. Увеличьте очередь и проверьте, успевает ли приложение отвечать." to "Connections not accepted: {1}, SYN dropped: {2}. Clients see a timeout when connecting. Increase the queue and check whether the application can keep up.",
    "Не совпадает ключ сервера — возможно, адрес подменён" to "The server key does not match — the address may have been swapped",
    "Не удалось {1} службу «{2}»: {3}" to "Failed to {1} the «{2}» service: {3}",
    "Не удалось выполнить действие: {1}" to "Failed to perform the action: {1}",
    "Не удалось заблокировать {1}: {2}" to "Failed to ban {1}: {2}",
    "Не удалось записать событие: {1}" to "Failed to record the event: {1}",
    "Не удалось обнулить журнал событий: {1}" to "Failed to clear the event log: {1}",
    "Не удалось обратиться к серверу" to "Could not reach the server",
    "Не удалось определить адрес узла" to "Could not resolve the host address",
    "Не удалось определить адрес узла (проверьте DNS)" to "Could not resolve the host address (check DNS)",
    "Не удалось открыть ссылку: {1}" to "Could not open the link: {1}",
    "Не удалось отправить оповещение: {1}" to "Failed to send the notification: {1}",
    "Не удалось поделиться отчётом: {1}" to "Could not share the report: {1}",
    "Не удалось поделиться файлом: {1}" to "Could not share the file: {1}",
    "Не удалось подключиться" to "Connection failed",
    "Не удалось подключиться к {1} — {2}" to "Could not connect to {1} — {2}",
    "Не удалось получить данные безопасности: {1}" to "Failed to get security data: {1}",
    "Не удалось получить данные обслуживания: {1}" to "Failed to get maintenance data: {1}",
    "Не удалось получить диагностику сети: {1}" to "Failed to get network diagnostics: {1}",
    "Не удалось получить состояние служб: {1}" to "Failed to get service status: {1}",
    "Не удалось почистить историю: {1}" to "Failed to clean the history: {1}",
)
