package ru.serverastus.monitor.данные.локаль

// Сгенерировано: 143 строк словаря (фрагмент 5).
internal val ЧастьАнглийский5: Map<String, String> = mapOf(
    "Чтобы видеть износ и переназначенные сектора, установите smartmontools: sudo apt install smartmontools" to "To see wear and reallocated sectors, install smartmontools: sudo apt install smartmontools",
    "Шаг {1} из {2}: {3}" to "Step {1} of {2}: {3}",
    "Экспорт CSV" to "Export CSV",
    "Экспорт CSV: {1} строк метрик, {2} строк проверок" to "CSV export: {1} metric rows, {2} check rows",
    "Экспорт не удался" to "Export failed",
    "Экспорт создаёт «метрики.csv» и «проверки.csv» в папке «экспорт» каталога приложения." to "The export creates «метрики.csv» and «проверки.csv» in the «экспорт» folder of the application directory.",
    "Эта служба уже добавлена" to "This service has already been added",
    "Это {1} из {2} пакетов, принятых за последний опрос — ядро не успевает разбирать очередь сетевой карты. Увеличьте net.core.netdev_max_backlog и число очередей карты." to "This is {1} of {2} packets received in the last poll — the kernel cannot drain the NIC queue fast enough. Increase net.core.netdev_max_backlog and the number of NIC queues.",
    "Это {1} из {2} пакетов, принятых за последний опрос, но программная очередь приёма (/proc/net/softnet_stat) потерь не показывает, а net.core.netdev_max_backlog уже {3} — дело не в переполнении очереди. Чаще всего так выглядят кадры, для которых у ядра нет обработчика: служебные кадры роутера (LLDP, IEEE1905.1, 802.3 XID) и пакеты, отклонённые файрволом. Проверить, что именно отбрасывается (пока идёт захват, счётчик не растёт — так устроено ядро):" to "This is {1} of {2} packets received in the last poll, but the software receive queue (/proc/net/softnet_stat) shows no losses and net.core.netdev_max_backlog is already {3} — the queue is not overflowing. Most often these are frames the kernel has no handler for: router service frames (LLDP, IEEE1905.1, 802.3 XID) and packets rejected by the firewall. To see what exactly is being dropped (the counter does not grow while the capture is running — that is how the kernel works):",
    "Это исправления уязвимостей. Их ставят в первую очередь, отдельно от остальных обновлений." to "These are vulnerability fixes. They are installed first, separately from other updates.",
    "Это оценка apt, а не приговор: столько пакетов помечены как автоматически установленные и остались без хозяина — обычно устаревшие библиотеки (Node.js, X11, perl). Среди них бывает ядро для отката или библиотека живого проекта, поэтому перед удалением рекомендуется проверить список." to "This is apt's estimate, not a verdict: that many packages are marked as automatically installed and left without an owner — usually outdated libraries (Node.js, X11, perl). The list may include a fallback kernel or a library used by a live project, so it is worth reviewing the list before removing.",
    "Это последний сервер: после удаления показывать будет нечего, и приложение снова откроет мастер настройки." to "This is the last server: after deletion there is nothing to show, and the app opens the setup wizard again.",
    "Это только журнал ядра и служб. Его стоит ограничить — иначе он съест диск раньше, чем вы это заметите." to "This is only the kernel and services journal. It is worth capping — otherwise it will eat up the disk before you notice.",
    "Этот порт уже добавлен" to "This port has already been added",
    "Этот сайт уже добавлен" to "This site has already been added",
    "Юнитов в автозапуске" to "Units in autostart",
    "Ядер" to "Kernels",
    "Ядро" to "Kernel",
    "Ядро включило SYN-cookies из-за переполнения очереди SYN — чаще всего это перебор портов (в том числе со стороны fail2ban) или флуд. Соединения при этом теряют часть параметров." to "The kernel enabled SYN-cookies because the SYN queue overflowed — most often it is port scanning (including from fail2ban) or a flood. Connections lose some parameters as a result.",
    "Ядро повторно отправляет сегменты — значит пакеты теряются по пути. Проверьте загрузку канала, ошибки интерфейса ниже и качество линии у провайдера." to "The kernel resends segments — so packets are being lost en route. Check the link load, the interface errors below and the line quality at your provider.",
    "Ядро работает" to "Running kernel",
    "Ядро установлено" to "Installed kernel",
    "Ядру не хватало памяти под TCP" to "The kernel ran out of memory for TCP",
    "адрес не задан" to "no address",
    "адрес сервера" to "server address",
    "без имени" to "unnamed",
    "блокировок: {1}" to "bans: {1}",
    "в порядке важности — сверху то, что даёт больше всего" to "in order of importance — the biggest wins on top",
    "важно" to "important",
    "важных: {1}" to "important: {1}",
    "включено" to "enabled",
    "внимание" to "attention",
    "внутренняя ошибка сервера (ошибка в коде сайта)" to "internal server error (a bug in the site's code)",
    "вращение" to "rotation",
    "всего {1}, TCP {2} (установлено {3})" to "total {1}, TCP {2} (established {3})",
    "всего: {1}" to "total: {1}",
    "всего: {1} · сбоев: {2}" to "total: {1} · failures: {2}",
    "всё работает" to "everything works",
    "выключено" to "disabled",
    "выполняется: {1}" to "in progress: {1}",
    "да" to "yes",
    "данных нет" to "no data",
    "диск {1}" to "disk {1}",
    "добавлено" to "added",
    "доступ запрещён" to "access denied",
    "дыхание" to "breathing",
    "есть проблемы" to "there are problems",
    "есть сбои" to "there are failures",
    "ещё не было" to "none yet",
    "заблокированные вручную с этой вкладки IP-адреса" to "IP addresses banned manually from this tab",
    "замечаний: {1}" to "findings: {1}",
    "запускается" to "starting",
    "запустить" to "start",
    "запущена" to "running",
    "какие диски есть, куда смонтированы и как себя чувствуют" to "which drives exist, where they are mounted and how they are doing",
    "код возврата {1}" to "return code {1}",
    "код ответа {1}" to "response code {1}",
    "крутилка" to "spinner",
    "кто пытался подобрать пароль по SSH и был заблокирован fail2ban" to "who tried to brute-force the SSH password and was banned by fail2ban",
    "лампа" to "lamp",
    "линия DOWN" to "link DOWN",
    "линия UP" to "link UP",
    "линк опущен: {1}" to "link down: {1}",
    "логин не задан" to "no login",
    "метод не разрешён" to "method not allowed",
    "модель неизвестна" to "model unknown",
    "например, 203.0.113.5" to "for example, 203.0.113.5",
    "наработка {1} ч" to "run time {1} h",
    "не используется" to "not used",
    "не найдена" to "not found",
    "не синхронизировано" to "not synchronised",
    "не указан" to "not set",
    "неверный запрос" to "bad request",
    "недоступно" to "unavailable",
    "неизвестная ошибка" to "unknown error",
    "неизвестно" to "unknown",
    "нет" to "no",
    "нет smartmontools" to "no smartmontools",
    "нет данных" to "no data",
    "нет ответа" to "no response",
    "нормально" to "normal",
    "нужна перезагрузка" to "reboot required",
    "обновления ядра и системы" to "kernel and system updates",
    "обновления, службы, журналы, время и диски" to "updates, services, journals, time and drives",
    "останавливается" to "stopping",
    "остановить" to "stop",
    "остановлена" to "stopped",
    "отлично" to "excellent",
    "ошибок за опрос {1}" to "errors per poll {1}",
    "пауза" to "paused",
    "перезагрузка не нужна" to "no reboot required",
    "перезапустить" to "restart",
    "перезапущена" to "restarted",
    "переназначено секторов: {1}" to "reallocated sectors: {1}",
    "переполнения, память TCP и таблица соединений" to "overflows, TCP memory and the connection table",
    "перечитывает настройки" to "reloading configuration",
    "плохо" to "poor",
    "по настройке «хранить_дней»" to "according to the «хранить_дней» setting",
    "показан сейчас" to "shown now",
    "полная блокировка адреса на сервере (все порты, через ufw)" to "full ban of the address on the server (all ports, via ufw)",
    "полный дуплекс" to "full duplex",
    "полудуплекс" to "half duplex",
    "порог {1}%" to "threshold {1}%",
    "порт {1}" to "port {1}",
    "потери: {1}" to "losses: {1}",
    "правило ufw №{1}" to "ufw rule #{1}",
    "проблемы: {1}" to "problems: {1}",
    "работает" to "running",
    "рекомендации по обслуживанию — от важных к необязательным" to "maintenance recommendations — from important to optional",
    "с {1}" to "since {1}",
    "сбоев: {1}" to "failures: {1}",
    "сбой" to "failure",
    "сбойные юниты, синхронизация часов и старт системы" to "failed units, clock synchronisation and system boot",
    "сведения" to "info",
    "сервер не дождался запроса" to "the server did not receive the request in time",
    "сервер не поддерживает запрошенный метод" to "the server does not support the requested method",
    "сервер_история.db" to "сервер_история.db",
    "сервис" to "service",
    "сеть" to "network",
    "синхронизировано" to "synchronised",
    "слишком много запросов, включилось ограничение" to "too many requests, rate limiting engaged",
    "служба недоступна: сервер перегружен или на обслуживании" to "service unavailable: the server is overloaded or under maintenance",
    "службы в порядке" to "services are in order",
    "смонтирован" to "mounted",
    "совет" to "advice",
    "совместимо с настольной версией" to "compatible with the desktop version",
    "сокетов: {1}" to "sockets: {1}",
    "спокойно" to "calm",
    "среднее {1} · максимум {2}" to "average {1} · maximum {2}",
    "страница не найдена" to "page not found",
    "строк: {1}" to "rows: {1}",
    "счётчики TCP и UDP, очереди и параметры ядра сервера" to "TCP and UDP counters, queues and the server's kernel parameters",
    "счётчики накопительные — с момента запуска сервера" to "counters are cumulative — since the server started",
    "текущие значения на сервере (меняются через sysctl)" to "current values on the server (changed via sysctl)",
    "трафик за время работы и потери на приёме" to "traffic since boot and receive losses",
    "трафик за время работы, состояние линии и потери на приёме" to "traffic since boot, link state and receive losses",
    "требуется авторизация" to "authorisation required",
    "чисто" to "clean",
    "что занимает диск и как быстро растут журналы" to "what takes up the disk and how fast the journals grow",
    "шлюз не дождался ответа от сервера приложения" to "the gateway did not receive a response from the application server",
    "шлюз получил неверный ответ от сервера приложения" to "the gateway received an invalid response from the application server",
    "• {1}" to "• {1}",
    "↓ {1} ↑ {2}" to "↓ {1} ↑ {2}",
)
