package ru.serverastus.monitor.данные.локаль

// Сгенерировано: 200 строк словаря (фрагмент 3).
internal val ЧастьАнглийский3: Map<String, String> = mapOf(
    "Не удалось прочитать config.json" to "Could not read config.json",
    "Не удалось прочитать историю: {1}" to "Failed to read the history: {1}",
    "Не удалось прочитать файл ключа «{1}» — {2}" to "Could not read the key file «{1}» — {2}",
    "Не удалось снять блокировку {1}: {2}" to "Failed to lift the ban for {1}: {2}",
    "Не удалось сохранить метрики: {1}" to "Failed to save metrics: {1}",
    "Не удалось сохранить проверку «{1}»: {2}" to "Failed to save the check «{1}»: {2}",
    "Не указан адрес сервера (хост)" to "The server address (host) is not set",
    "Не указан ни пароль, ни файл ключа — подключиться не получится" to "Neither a password nor a key file is set — connecting will not work",
    "Не указан пользователь сервера" to "The server user is not set",
    "Не указано имя службы" to "The service name is not set",
    "Не установлен smartmontools, поэтому состояние накопителей неизвестно. Пакет маленький, но показывает износ и переназначенные сектора." to "smartmontools is not installed, so the state of the drives is unknown. The package is small but shows wear and reallocated sectors.",
    "Ненужных пакетов" to "Unneeded packages",
    "Ненужных пакетов: {1}" to "Unneeded packages: {1}",
    "Нет данных" to "No data",
    "Нет данных — откройте приложение" to "No data — open the app",
    "Нет контроля здоровья дисков" to "No drive health monitoring",
    "Нет связи с сервером по SSH: {1}" to "No SSH connection to the server: {1}",
    "Неудачных открытий" to "Failed opens",
    "Ничего не нашлось — добавьте адреса вручную выше. Так бывает, если сайты обслуживает не nginx и не Apache." to "Nothing was found — add the addresses manually above. This happens when the sites are served by neither nginx nor Apache.",
    "Новый сервер" to "New server",
    "Новых соединений" to "New connections",
    "Номер порта, например 443" to "Port number, for example 443",
    "О приложении" to "About",
    "ОЗУ" to "RAM",
    "ОЗУ {1}" to "RAM {1}",
    "ОЗУ всего, байт" to "RAM total, bytes",
    "ОЗУ занято, байт" to "RAM used, bytes",
    "ОС" to "OS",
    "Обновить" to "Refresh",
    "Обновить сейчас" to "Refresh now",
    "Обновлений доступно" to "Updates available",
    "Обновления безопасности" to "Security updates",
    "Обновления безопасности: {1}" to "Security updates: {1}",
    "Обновления пакетов" to "Package updates",
    "Обновления установлены, службы здоровы, журналы под контролем." to "Updates are installed, services are healthy, journals are under control.",
    "Обновлено" to "Updated",
    "Обновлено {1}" to "Updated {1}",
    "Обновлено: {1}" to "Updated: {1}",
    "Обнулить" to "Reset",
    "Обнулить журнал" to "Reset journal",
    "Обнулить журнал событий?" to "Reset the event journal?",
    "Обработайте важные советы ниже — и оценка вернётся в норму." to "Work through the important advice below — the score will return to normal.",
    "Обслуживание" to "Maintenance",
    "Обслуживание сервера" to "Server maintenance",
    "Обслуживание сервера (обновления, журналы, диски)" to "Server maintenance (updates, journals, drives)",
    "Обслуживание сервера · {1}" to "Server maintenance · {1}",
    "Обслуживание сервера снова в норме: оценка {1} из 100 ({2})" to "Server maintenance is back to normal: score {1} of 100 ({2})",
    "Ожидаемые коды через запятую" to "Expected codes, comma-separated",
    "Ожидание закрытия соединения" to "Connection close wait",
    "Окно очищено — ждём новых событий" to "Window cleared — waiting for new events",
    "Окно приложения открыто" to "Application window opened",
    "Опрос Linux-сервера выключен в настройках" to "Linux server polling is disabled in the settings",
    "Опрос запущен" to "Polling started",
    "Остановить" to "Stop",
    "Отброшено SYN" to "SYN dropped",
    "Отброшено SYN: {1} (за время работы сервера)" to "SYN dropped: {1} (since server start)",
    "Отброшено пакетов на «{1}»: {2} за всё время работы" to "Packets dropped on «{1}»: {2} since boot",
    "Отброшено пакетов на «{1}»: {2} за опрос" to "Packets dropped on «{1}»: {2} this poll",
    "Ответ" to "Response",
    "Отдача крупных ответов ограничена размером буфера — поднимите предел для дальних клиентов." to "Sending large responses is limited by the buffer size — raise the limit for distant clients.",
    "Открытий активных / пассивных" to "Active / passive opens",
    "Открытые порты" to "Open ports",
    "Открытых портов не найдено: сервер не показал список слушающих портов" to "No open ports found: the server did not return the list of listening ports",
    "Открыть" to "Open",
    "Открыть сайт разработчика" to "Open the developer's site",
    "Отмена" to "Cancel",
    "Отменить правки" to "Discard changes",
    "Отправлено всего" to "Sent total",
    "Отправлять в Telegram" to "Send to Telegram",
    "Отправлять на вебхук" to "Send to webhook",
    "Отчёт скопирован в буфер обмена" to "Report copied to clipboard",
    "Оценка: {1} из 100" to "Score: {1} of 100",
    "Оценка: {1} из 100 — {2}" to "Score: {1} of 100 — {2}",
    "Очереди, сбои и сокеты" to "Queues, failures and sockets",
    "Очереди, сбои и таблицы" to "Queues, failures and tables",
    "Очередь SYN ({1}) меньше очереди соединений ({2})" to "SYN queue ({1}) is smaller than the connection queue ({2})",
    "Очередь «полуоткрытых» соединений" to "Half-open connection queue",
    "Очередь входящих соединений" to "Incoming connection queue",
    "Очередь приёма сетевой карты" to "NIC receive queue",
    "Очистить окно" to "Clear window",
    "Ошибка" to "Error",
    "Ошибка SSL: {1}" to "SSL error: {1}",
    "Ошибка аудита обслуживания: {1}" to "Maintenance audit error: {1}",
    "Ошибка диагностики сети: {1}" to "Network diagnostics error: {1}",
    "Ошибка опроса: {1}" to "Polling error: {1}",
    "Ошибка проверки SSL-сертификата" to "SSL certificate verification error",
    "Ошибка сбора данных безопасности: {1}" to "Security data collection error: {1}",
    "Ошибка сбора метрик: {1}" to "Metrics collection error: {1}",
    "Ошибка связи" to "Connection error",
    "Ошибка соединения: {1}" to "Connection error: {1}",
    "Ошибка: {1}" to "Error: {1}",
    "Ошибки линии на «{1}»" to "Link errors on «{1}»",
    "Ошибки линии на «{1}»: {2} за всё время работы" to "Link errors on «{1}»: {2} since boot",
    "Ошибки линии на «{1}»: {2} за опрос" to "Link errors on «{1}»: {2} per poll",
    "Ошибки приёма / отправки" to "Receive / send errors",
    "Ошибки приёма UDP: {1}" to "UDP receive errors: {1}",
    "Ошибки приёма и отправки растут прямо сейчас — за последний опрос их {1}. Обычно это битые кадры: проверьте кабель, порт коммутатора и настройки скорости/дуплекса." to "Receive and transmit errors are growing right now — {1} in the last poll. Usually these are corrupted frames: check the cable, the switch port and the speed/duplex settings.",
    "Ошибок и отбросов на внешних интерфейсах нет." to "No errors or drops on external interfaces.",
    "Ошибок контрольных сумм" to "Checksum errors",
    "Ошибок линии нет, потерь за последний опрос тоже — отброшенные пакеты набрались раньше." to "No link errors and no losses in the last poll either — the dropped packets accumulated earlier.",
    "Ошибок приёма" to "Receive errors",
    "Ошибок приёма {1}, отправки {2}, но за последний опрос не прибавилось ни одной — счётчик набран раньше. Следим за приростом, а не за накопленным значением." to "Receive errors {1}, transmit errors {2}, but not a single one was added in the last poll — the counter was accumulated earlier. What matters is the increase, not the total.",
    "Ошибок приёма {1}, отправки {2}. Обычно это битые кадры: проверьте кабель, порт коммутатора и настройки скорости/дуплекса." to "Receive errors {1}, send errors {2}. These are usually damaged frames: check the cable, the switch port and the speed/duplex settings.",
    "Ошибок приёма сегментов" to "Segment receive errors",
    "Пакетов UDP" to "UDP packets",
    "Память" to "Memory",
    "Память TCP в страницах (мин/давление/макс)" to "TCP memory in pages (min/pressure/max)",
    "Память под TCP" to "Memory for TCP",
    "Панель" to "Dashboard",
    "Параметры сети в порядке — вмешательство не требуется. Продолжайте следить за долей повторных передач и потерями на интерфейсах." to "Network parameters are in order — no intervention needed. Keep an eye on the retransmission share and interface losses.",
    "Параметры ядра" to "Kernel parameters",
    "Пароль" to "Password",
    "Пароль в файл config.json не записывается: он лежит в защищённом хранилище Android (Keystore) и в настройках видна только отметка о том, что пароль сохранён." to "The password is never written to config.json: it lives in Android's secure store (Keystore), and the settings only show that a password is saved.",
    "Пароль хранится в config.json открытым текстом — так же, как в настольной версии. Файл ключа нужно положить в каталог приложения." to "The password is stored in config.json as plain text — just like in the desktop version. The key file must be placed in the application directory.",
    "Пароль хранится в защищённом хранилище телефона, а не в config.json: в файле остаётся только ссылка на секрет. Файл ключа нужно положить в каталог приложения." to "The password is kept in the phone's secure store rather than in config.json: the file only holds a reference to the secret. The key file has to be placed into the app folder.",
    "Пароль хранится в файле config.json на этом телефоне в открытом виде — так же, как в настольной версии. Не передавайте телефон посторонним." to "The password is stored in the config.json file on this phone in plain text — just like in the desktop version. Do not hand the phone to strangers.",
    "Пауза" to "Pause",
    "Перезапустить" to "Restart",
    "Переиспользование TIME_WAIT" to "TIME_WAIT reuse",
    "Переполнение очереди входящих соединений" to "Incoming connection queue overflow",
    "Переполнений буфера" to "Buffer overflows",
    "Переполнений очереди прослушивания" to "Listen queue overflows",
    "ПиБ" to "PiB",
    "Планировщик очереди по умолчанию" to "Default queue scheduler",
    "Повторные передачи TCP: {1} %" to "TCP retransmissions: {1} %",
    "Повторных передач" to "Retransmissions",
    "Повторных передач в минуту" to "Retransmissions per minute",
    "Повторных передач за замер" to "Retransmissions per sample",
    "Повторы в /etc/fstab" to "Duplicates in /etc/fstab",
    "Повторяющиеся точки монтирования в fstab" to "Duplicate mount points in fstab",
    "Повышенная доля повторных передач: {1} %" to "Elevated retransmission share: {1} %",
    "Поделиться отчётом" to "Share report",
    "Подкачка" to "Swap",
    "Подкачка занята" to "Swap in use",
    "Подкачка занята на {1} %" to "Swap used: {1} %",
    "Подключение к серверу по SSH" to "Connecting to the server over SSH",
    "Подробные данные (процессы, температура)" to "Detailed data (processes, temperature)",
    "Подтвердите действие" to "Confirm the action",
    "Поиск работающих служб" to "Search for running services",
    "Поиск сайтов на сервере" to "Search for sites on the server",
    "Поиск слушающих портов" to "Search for listening ports",
    "Пока пусто" to "Empty so far",
    "Показать" to "Show",
    "Показать службы на сервере" to "Show services on the server",
    "Показывать уведомления на телефоне" to "Show notifications on the phone",
    "Показываются только запущенные службы. Служебные юниты systemd скрыты, чтобы список был короче." to "Only running services are shown. systemd internal units are hidden to keep the list short.",
    "Показываются только порты, доступные извне (0.0.0.0 или ::). Порты с привязкой к localhost пропускаются." to "Only ports reachable from outside are shown (0.0.0.0 or ::). Ports bound to localhost are skipped.",
    "Полная выгрузка истории — CSV-файлы в папке «экспорт» рядом с настройками." to "Full history export — CSV files in the «экспорт» folder next to the settings.",
    "Получено всего" to "Received total",
    "Пользователь" to "User",
    "Пороги предупреждений, %" to "Warning thresholds, %",
    "Порт" to "Port",
    "Порт SSH" to "SSH port",
    "Порт SSH должен быть от 1 до 65535" to "The SSH port must be between 1 and 65535",
    "Порт {1}" to "Port {1}",
    "Порт {1} ({2})" to "Port {1} ({2})",
    "Порт не отвечает ({1} с)" to "Port is not responding ({1} s)",
    "Портов" to "Ports",
    "Порты" to "Ports",
    "Порты: {1}" to "Ports: {1}",
    "После каждой паузы соединение снова начинает с малой скорости. Для сайтов с короткими запросами выгоднее выключить: соединения уже «разогреты»." to "After every pause the connection starts again from a low rate. For sites with short requests it is better to disable it: the connections are already «warmed up».",
    "Последние {1} проверок" to "Last {1} checks",
    "Последние события" to "Latest events",
    "Последний опрос" to "Last poll",
    "Последняя проверка" to "Last check",
    "Потерь за один снимок не измерить — доля появится со следующего опроса." to "Losses cannot be measured from a single snapshot — the share will appear from the next poll.",
    "Потерь за последний опрос нет — счётчик набран раньше и на работу сервисов сейчас не влияет. Обнулится при перезагрузке сервера." to "No losses in the last poll — the counter accumulated earlier and does not affect the services right now. It resets when the server reboots.",
    "Потеряно повторных передач" to "Retransmissions lost",
    "Потеряно повторных передач: {1}" to "Retransmissions lost: {1}",
    "Превышено время ожидания ({1} с)" to "Timed out ({1} s)",
    "Превышено время ожидания ответа" to "Response timed out",
    "Превышено время ожидания чтения ответа" to "Timed out while reading the response",
    "Предел соединений TIME_WAIT" to "TIME_WAIT connection limit",
    "Предел таблицы соединений" to "Connection table limit",
    "Предупреждение" to "Warning",
    "При всплеске подключений узкое место — очередь «полуоткрытых» соединений. Значения стоит уравнять." to "During a connection burst the bottleneck is the half-open connection queue. The values should be equalised.",
    "При всплеске трафика ядро начнёт отбрасывать пакеты ещё до обработки. Значение 4096 подходит для гигабитного канала." to "During a traffic burst the kernel will start dropping packets before processing. The value 4096 suits a gigabit link.",
    "Приветствие" to "Greeting",
    "Приложение" to "App",
    "Приложение запущено (Android {1}, {2})" to "App started (Android {1}, {2})",
    "Приложение показывает состояние службы и умеет её перезапустить. Для перезапуска нужны права sudo." to "The app shows the service state and can restart it. Restarting requires sudo rights.",
    "Приложение прочитает server_name в nginx и ServerName в Apache, а также проверит, есть ли на сервере HTTPS." to "The app reads server_name in nginx and ServerName in Apache, and also checks whether HTTPS is available on the server.",
    "Приложение следит за вашим Linux-сервером: процессор, оперативная память, диски и сеть, доступность сайтов и портов, состояние служб systemd и защита fail2ban. Все настройки — только ваши: приложение ничего не знает о чужих серверах." to "The app watches your Linux server: CPU, RAM, disks and network, the availability of sites and ports, systemd service state and fail2ban protection. All settings are yours alone: the app knows nothing about anyone else's servers.",
    "Проблемы со здоровьем диска" to "Drive health problems",
    "Проверено {1}" to "Checked {1}",
    "Проверено: {1}" to "Checked: {1}",
    "Проверить Telegram" to "Test Telegram",
    "Проверить вебхук" to "Test webhook",
    "Проверить подключение" to "Test connection",
    "Проверить связь" to "Test connectivity",
    "Проверка «молчащих» соединений" to "«Silent» connection probing",
    "Проверка идёт мимо рабочих настроек: приложение откроет отдельное соединение и не сохранит ничего лишнего. Логин должен уметь читать /proc и запускать systemctl." to "The check bypasses your working settings: the app opens a separate connection and saves nothing extra. The login must be able to read /proc and run systemctl.",
    "Проверка порта — это обычное TCP-подключение к адресу сервера по указанному номеру." to "A port check is a plain TCP connection to the server address on the given number.",
    "Проверка связи" to "Connection test",
    "Проверка связи: {1}" to "Connectivity check: {1}",
    "Проверки" to "Checks",
    "Проверки ещё не выполнялись" to "No checks have been run yet",
    "Проверьте настройки" to "Check the settings",
    "Проверьте, что это не ваш собственный IP — иначе вы потеряете доступ к серверу по SSH и к сайтам с этого адреса." to "Make sure this is not your own IP — otherwise you will lose SSH access to the server and to the sites from this address.",
    "Проверять срок SSL-сертификата" to "Check SSL certificate expiry",
)
