package ru.serverastus.monitor.данные.локаль

// Сгенерировано: 200 строк словаря (фрагмент 1).
internal val ЧастьАнглийский1: Map<String, String> = mapOf(
    "     {1}" to "     {1}",
    "     Команда: {1}" to "     Command: {1}",
    "     Состояние: {1}" to "     State: {1}",
    "    {1}  {2}" to "    {1}  {2}",
    "  SMART: {1}" to "  SMART: {1}",
    "  SYN-cookies включены: {1}" to "  SYN-cookies enabled: {1}",
    "  TIME_WAIT: {1}, осиротевших: {2}" to "  TIME_WAIT: {1}, orphaned: {2}",
    "  apt установит сейчас: {1}" to "  apt will install now: {1}",
    "  {1}" to "  {1}",
    "  {1} — {2}, {3}{4}" to "  {1} — {2}, {3}{4}",
    "  {1}. {2}{3}" to "  {1}. {2}{3}",
    "  {1}: {2}" to "  {1}: {2}",
    "  {1}: принято {2}, отправлено {3}, пакетов {4}, отброшено {5}{6}{7}" to "  {1}: received {2}, sent {3}, packets {4}, dropped {5}{6}{7}",
    "  Автообновления безопасности: {1}" to "  Security auto-updates: {1}",
    "  Аптайм: {1}" to "  Uptime: {1}",
    "  Датаграмм отправлено: {1}" to "  Datagrams sent: {1}",
    "  Датаграмм принято: {1}" to "  Datagrams received: {1}",
    "  Доля повторных передач: {1} %" to "  Retransmission share: {1} %",
    "  Доступно обновлений: {1}" to "  Updates available: {1}",
    "  Журнал systemd: {1}" to "  systemd journal: {1}",
    "  За последний опрос: повторных передач {1} из {2} сегментов — {3} %" to "  Last poll: {1} retransmissions of {2} segments — {3} %",
    "  Загрузка: {1} с" to "  Load: {1} s",
    "  Закрытий из-за нехватки памяти: {1}, срабатываний ограничителя: {2}" to "  Closed due to memory shortage: {1}, limit hits: {2}",
    "  Замечаний нет — сервер обслуживается аккуратно." to "  No findings — the server is well maintained.",
    "  Из них безопасности: {1}" to "  Security updates among them: {1}",
    "  Кандидатов на автоматическое удаление: {1}" to "  Candidates for automatic removal: {1}",
    "  Каталог /var/log: {1}" to "  /var/log directory: {1}",
    "  Команда: {1}" to "  Command: {1}",
    "  На закрытые порты: {1}" to "  To closed ports: {1}",
    "  Ненужных пакетов: {1}" to "  Unneeded packages: {1}",
    "  Неудачных открытий: {1}" to "  Failed opens: {1}",
    "  Новых соединений: {1}/с, повторных передач: {2}/мин" to "  New connections: {1}/s, retransmissions: {2}/min",
    "  Отброшено SYN: {1}, в бэклоге: {2}" to "  SYN dropped: {1}, in backlog: {2}",
    "  Открытий активных/пассивных: {1} / {2}" to "  Active/passive opens: {1} / {2}",
    "  Ошибок контрольных сумм: {1}" to "  Checksum errors: {1}",
    "  Ошибок приёма сегментов: {1}" to "  Segment receive errors: {1}",
    "  Ошибок приёма: {1}" to "  Receive errors: {1}",
    "  Пакетов: {1}/с" to "  Packets: {1}/s",
    "  Переполнений буфера приёма/отправки: {1} / {2}" to "  Receive/send buffer overflows: {1} / {2}",
    "  Переполнений очереди прослушивания: {1}" to "  Listen queue overflows: {1}",
    "  Повторных передач: {1}" to "  Retransmissions: {1}",
    "  Повторы в /etc/fstab: {1}" to "  Duplicates in /etc/fstab: {1}",
    "  Подкачка занята на {1} %" to "  Swap used: {1} %",
    "  Раздел занят на {1} % (свободно {2} из {3})" to "  Partition used: {1} % ({2} free of {3})",
    "  Ротация журналов: {1}" to "  Log rotation: {1}",
    "  Сбойных юнитов: {1}" to "  Failed units: {1}",
    "  Сбросов соединений: {1}" to "  Connection resets: {1}",
    "  Сегментов отправлено: {1}" to "  Segments sent: {1}",
    "  Сегментов принято: {1}" to "  Segments received: {1}",
    "  Синхронизация времени: {1}" to "  Time syncing: {1}",
    "  Служба времени: {1}" to "  Time service: {1}",
    "  Слушающих портов: {1}" to "  Listening ports: {1}",
    "  Соединений установлено сейчас: {1}" to "  Connections established now: {1}",
    "  Сокетов всего: {1}, TCP: {2}, UDP: {3}" to "  Sockets total: {1}, TCP: {2}, UDP: {3}",
    "  Таблица соединений: {1} из {2} ({3})" to "  Connection table: {1} of {2} ({3})",
    "  Таймаутов TCP: {1}, потеряно повторных передач: {2}" to "  TCP timeouts: {1}, retransmissions lost: {2}",
    "  Требуется перезагрузка: да" to "  Reboot required: yes",
    "  Установлено пакетов: {1}, автозапуск юнитов: {2}" to "  Packages installed: {1}, unit autostart: {2}",
    "  Установлено ядро: {1}" to "  Kernel installed: {1}",
    "  Часовой пояс: {1}" to "  Time zone: {1}",
    "  Ядро: {1}" to "  Kernel: {1}",
    " ({1} отброшено)" to " ({1} dropped)",
    " ({1})" to " ({1})",
    " (пользователю нужно право на sudo)" to " (the user needs sudo rights)",
    " {1}" to " {1}",
    " · {1}" to " · {1}",
    " · {1} мс" to " · {1} ms",
    " · на паузе" to " · paused",
    " · пауза" to " · paused",
    " — {1}" to " — {1}",
    "+ Добавить сервер" to "+ Add server",
    ", {1}" to ", {1}",
    ", ОС: {1}" to ", OS: {1}",
    ", за опрос отброшено {1} из {2} пакетов — {3}" to ", {1} of {2} packets dropped this poll — {3}",
    ", ядро {1}" to ", kernel {1}",
    ". Главное: {1}" to ". Main issue: {1}",
    "/var/log без журнала занимает {1}" to "/var/log without the systemd journal takes {1}",
    "/var/log занимает {1}" to "/var/log occupies {1}",
    "/с" to "/s",
    "APT считает {1} кандидатами на автоматическое удаление" to "APT considers {1} candidates for automatic removal",
    "BBR не загружен (доступно: {1}). Загрузите модуль ядра — на Ubuntu он в пакете linux-modules-extra, при ошибке modprobe поставьте его: apt-get install -y linux-modules-extra-\$(uname -r)" to "BBR is not loaded (available: {1}). Load the kernel module — on Ubuntu it lives in the linux-modules-extra package; if modprobe fails, install it: apt-get install -y linux-modules-extra-\$(uname -r)",
    "Cloudflare: веб-сервер не отвечает" to "Cloudflare: the web server is not responding",
    "Cloudflare: не удалось выполнить SSL-рукопожатие с сервером" to "Cloudflare: SSL handshake with the server failed",
    "Cloudflare: недействительный SSL-сертификат сервера" to "Cloudflare: invalid SSL certificate on the server",
    "Cloudflare: ошибка DNS или неверный заголовок запроса" to "Cloudflare: DNS error or invalid request header",
    "Cloudflare: ошибка соединения Railgun" to "Cloudflare: Railgun connection error",
    "Cloudflare: превышено время ожидания от сервера-источника" to "Cloudflare: origin server timed out",
    "Cloudflare: сервер вернул неизвестную ошибку" to "Cloudflare: the server returned an unknown error",
    "Cloudflare: сервер-источник недоступен" to "Cloudflare: origin server unreachable",
    "Cloudflare: соединение с сервером не установлено" to "Cloudflare: no connection to the server",
    "HTTP-альт." to "HTTP alt.",
    "HTTPS-альт." to "HTTPS alt.",
    "IP {1} заблокирован" to "IP {1} is blocked",
    "IP-адрес" to "IP address",
    "SMART в норме" to "SMART is healthy",
    "SMART сообщает о неисправности: {1}. Такой диск может отказать в любой момент — сделайте копию данных и готовьте замену." to "SMART reports a failure: {1}. Such a drive may fail at any moment — back up your data and prepare a replacement.",
    "SSL, дней" to "SSL, days",
    "SYN-cookies включены" to "SYN-cookies enabled",
    "ServerMonitor для Android" to "ServerMonitor for Android",
    "TCP (счётчики с момента запуска сервера)" to "TCP (counters since server start)",
    "TCP-проверка молчащих соединений — {1} с" to "TCP keepalive probe — {1} s",
    "TIME_WAIT: {1} соединений" to "TIME_WAIT: {1} connections",
    "TIME_WAIT: {1} соединений при выключенном переиспользовании" to "TIME_WAIT: {1} connections with reuse disabled",
    "UDP на закрытые порты: {1}" to "UDP to closed ports: {1}",
    "[важно] " to "[important] ",
    "apt установит сейчас" to "apt will install now",
    "fail2ban заблокировал подозрительный IP {1} (jail «{2}») — похоже на подбор пароля/атаку" to "fail2ban banned suspicious IP {1} (jail «{2}») — looks like a password brute-force attack",
    "fail2ban снял временную блокировку с {1} (jail «{2}»)" to "fail2ban unbanned {1} (jail «{2}»)",
    "fail2ban — защита от подбора пароля по SSH" to "fail2ban — protection against SSH password brute force",
    "http://{1}" to "http://{1}",
    "https://{1}" to "https://{1}",
    "jail «{1}»" to "jail «{1}»",
    "logrotate.timer неактивен: файлы в /var/log будут расти, пока не закончится место." to "logrotate.timer is inactive: files in /var/log will keep growing until the disk fills up.",
    "modprobe tcp_bbr && sysctl -w net.ipv4.tcp_congestion_control=bbr{1}" to "modprobe tcp_bbr && sysctl -w net.ipv4.tcp_congestion_control=bbr{1}",
    "sysctl -w net.core.netdev_max_backlog={1}" to "sysctl -w net.core.netdev_max_backlog={1}",
    "sysctl -w net.ipv4.tcp_mem=\"{1} {2} {3}\"" to "sysctl -w net.ipv4.tcp_mem=\"{1} {2} {3}\"",
    "sysctl -w net.netfilter.nf_conntrack_max={1}" to "sysctl -w net.netfilter.nf_conntrack_max={1}",
    "systemd считает эти юниты упавшими: {1}. Посмотрите причину и перезапустите — часто это служба, которую выключили, но пакет остался установлен." to "systemd considers these units failed: {1}. Check the cause and restart them — often the service was disabled but the package stayed installed.",
    "tcpdump -i {1} -e -nn -c 20 'not (ip or arp or ip6)'" to "tcpdump -i {1} -e -nn -c 20 'not (ip or arp or ip6)'",
    "unattended-upgrades устанавливает исправления уязвимостей сам, без вашего участия. Для сервера, к которому нет ежедневного доступа, это самая дешёвая страховка." to "unattended-upgrades applies vulnerability fixes on its own, without your involvement. For a server you don't access daily this is the cheapest insurance.",
    "{1} %" to "{1} %",
    "{1} % · свободно {2}" to "{1} % · free {2}",
    "{1} ({2})" to "{1} ({2})",
    "{1} ({2}): {3}" to "{1} ({2}): {3}",
    "{1} (проверок: {2})" to "{1} (checks: {2})",
    "{1} / {2}" to "{1} / {2}",
    "{1} / {2} / {3}" to "{1} / {2} / {3}",
    "{1} °C" to "{1} °C",
    "{1} · {2}" to "{1} · {2}",
    "{1} · {2}:{3}" to "{1} · {2}:{3}",
    "{1} · бэклог {2}" to "{1} · backlog {2}",
    "{1} · выбран" to "{1} · selected",
    "{1} · осиротевших {2}" to "{1} · orphaned {2}",
    "{1} · портов {2} · служб {3}" to "{1} · ports {2} · services {3}",
    "{1} Мбит/с" to "{1} Mbit/s",
    "{1} Часть обновлений безопасности вступает в силу только после перезагрузки." to "{1} Some security updates only take effect after a reboot.",
    "{1} вернулась в норму: {2}%" to "{1} is back to normal: {2}%",
    "{1} д" to "{1} d",
    "{1} дн." to "{1} d",
    "{1} достигла {2}% (порог {3}%)" to "{1} reached {2}% (threshold {3}%)",
    "{1} из {2}" to "{1} of {2}",
    "{1} из {2} ({3})" to "{1} of {2} ({3})",
    "{1} из {2} сегментов" to "{1} of {2} segments",
    "{1} мин" to "{1} min",
    "{1} мс" to "{1} ms",
    "{1} пакет" to "{1} package",
    "{1} пакета" to "{1} packages",
    "{1} пакетов" to "{1} packages",
    "{1} попыток · {2} блок." to "{1} attempts · {2} bans",
    "{1} с" to "{1} s",
    "{1} службу «{2}» на сервере?" to "{1} the «{2}» service on the server?",
    "{1} страниц" to "{1} pages",
    "{1} ч" to "{1} h",
    "{1} — {2}" to "{1} — {2}",
    "{1} — работает" to "{1} — running",
    "{1}.files" to "{1}.files",
    "{1}.service" to "{1}.service",
    "{1}/с" to "{1}/s",
    "{1}:{2}" to "{1}:{2}",
    "«{1}» не похоже на IP-адрес" to "«{1}» does not look like an IP address",
    "«{1}»: линия, скорость и режим" to "«{1}»: link, speed and mode",
    "«{1}»: отброшено за последний опрос" to "«{1}»: dropped in the last poll",
    "«{1}»: ошибки за последний опрос" to "«{1}»: errors in the last poll",
    "«{1}»: ошибки приёма / отправки (за всё время работы)" to "«{1}»: receive / transmit errors (since boot)",
    "«{1}»: пакеты / отброшено (за всё время работы)" to "«{1}»: packets / dropped (since boot)",
    "«Добавить сервер» открывает мастер настройки: он проверяет подключение и ищет сайты, порты и службы. Настройки уже добавленных серверов при этом не меняются." to "«Add server» opens the setup wizard: it tests the connection and looks for sites, ports and services. Settings of already added servers stay untouched.",
    "«Начать мониторинг» сохранит настройки и сразу опросит сервер. «Настроить позже» сохранит то, что вы уже ввели, но не станет опрашивать сервер сейчас." to "«Start monitoring» saves your settings and polls the server right away. «Set up later» saves what you have already entered but does not poll the server now.",
    "«Очистить окно» скрывает записи на экране, «Обнулить журнал» удаляет их из базы насовсем." to "«Clear window» hides the entries on screen; «Reset journal» deletes them from the database for good.",
    "Автообновления безопасности" to "Security auto-updates",
    "Автообновления безопасности выключены" to "Security auto-updates are disabled",
    "Адрес" to "Address",
    "Адрес (URL)" to "Address (URL)",
    "Адрес вебхука" to "Webhook address",
    "Адрес или домен" to "Address or domain",
    "Адрес сайта, например https://мой-сайт.ру" to "Site address, for example https://my-site.com",
    "Адрес сервера и порт SSH" to "Server address and SSH port",
    "Адреса, пароль и списки будут заменены значениями по умолчанию. После сброса откроется мастер настройки." to "Addresses, password and lists will be replaced with the default values. The setup wizard opens after the reset.",
    "Активно используется файл подкачки — значит памяти не хватает и сервер заметно тормозит на диск. Посмотрите, кто её занимает." to "A swap file is being used actively — your RAM is insufficient and the server slows down noticeably on disk I/O. Check what is consuming it.",
    "Активные блокировки" to "Active bans",
    "Активный сервер: {1}" to "Active server: {1}",
    "Аптайм" to "Uptime",
    "Аптайм, с" to "Uptime, s",
    "Б" to "B",
    "База истории" to "History database",
    "Безопасность" to "Security",
    "Безопасность (fail2ban, ufw)" to "Security (fail2ban, ufw)",
    "Блокировка {1} снята" to "Ban for {1} lifted",
    "Буферы отправки TCP (мин/по умолч./макс)" to "TCP send buffers (min/default/max)",
    "Буферы приёма TCP (мин/по умолч./макс)" to "TCP receive buffers (min/default/max)",
    "Быстрое открытие TCP (TFO)" to "TCP Fast Open (TFO)",
    "Быстрое открытие TCP (TFO) выключено" to "TCP Fast Open (TFO) is disabled",
    "В /etc/fstab несколько строк на одну точку ({1}). Оставьте одну запись — так меньше шансов запутаться при переезде или замене диска." to "/etc/fstab has several lines for the same mount point ({1}). Keep a single entry — that way it is harder to get confused when migrating or replacing a disk.",
    "В настройках не указан адрес сервера" to "The server address is not set in the settings",
    "В настройках не указан пользователь сервера" to "The server user is not set in the settings",
    "В приложении нет чужих настроек: адрес сервера, сайты, порты и службы задаёт владелец телефона — через мастер настройки или вручную на этой вкладке." to "The app holds nobody else's settings: the server address, sites, ports and services are set by the phone's owner — via the setup wizard or manually on this tab.",
    "Вернуться к мониторингу" to "Back to monitoring",
    "Версия" to "Version",
    "Вид" to "Type",
    "Включалась защита SYN-cookies: {1} раз" to "SYN-cookies protection engaged: {1} times",
    "Включён медленный старт после простоя" to "Slow start after idle is enabled",
)
